version: '2'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bla
      POSTGRES_PASSWORD: bla
      POSTGRES_DB: criticalmaps
    restart: always

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    volumes:
      - ./migrations/:/migrations/
    environment:
      DATABASE_URL: postgres://bla:bla@db/criticalmaps
    command:  ["up"]
    restart: on-failure
